# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
cache: cocoapods
podfile: Example/Podfile

# TODO: Uncomment these lines after Quick and Nimble updated their pod versions.

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update # Uncomment this when the pod install failed because of the stale pod repo
- pod install --project-directory=Example --verbose
script:
- set -o pipefail && xcodebuild
  -workspace Example/CascadingTableDelegate.xcworkspace
  -scheme CascadingTableDelegate-Example
  -destination 'platform=iOS Simulator,name=iPhone 5s'
  clean test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
- pod lib lint
